name: Python (and other) style checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ruff
        run: python3 -m pip install ruff
      - name: Run ruff check
        run: ruff check

  flake8-picky-parentheses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install flake8-picky-parentheses
        run: python3 -m pip install flake8 flake8-picky-parentheses
      - name: Run flake8 check
        run: |
          python3 -m flake8 \
            --isolated \
            --require-plugins flake8-picky-parentheses \
            --select PAR --extend-ignore PAR104

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install flake8-picky-parentheses
        run: python3 -m pip install yamllint
      - name: Run yamllint check
        run: |
          # document-start: don't care
          # truthy: triggers on keys named 'on:'
          # comments-indentation: falsely triggers if comment is separated by empty line
          python3 -m yamllint -d '
            extends: default
            locale: en_US.UTF-8
            yaml-files:
              - "*.yaml"
              - "*.yml"
              - "*.fmf"
            rules:
              document-start: disable
              truthy: disable
              comments-indentation: disable
              line-length:
                max: 99
              indentation:
                spaces: 2
              comments:
                require-starting-space: false
          ' .

  subtests-subresults:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure subtests are not named "subresults"
        run: |
          ! grep -r subresult *
